export const SECRET_ENVIRONMENT_NAMES: readonly [
  'ADMIN_API_TOKEN',
  'ADMIN_AUTH_CONFIG',
  'CF_API_KEY',
  'CF_API_TOKEN',
  'CF_ACCESS_CLIENT_SECRET',
  'CLOUDFLARE_ACCOUNT_ID',
  'CLOUDFLARE_API_KEY',
  'CLOUDFLARE_API_TOKEN',
  'CLOUDFLARE_ACCESS_CLIENT_SECRET',
  'CLOUDFLARE_EMAIL',
  'WRANGLER_API_TOKEN',
]

export function createSecretFreeEnvironment(source: NodeJS.ProcessEnv): NodeJS.ProcessEnv
